# Generated by Django 4.2.1 on 2023-11-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandboxapp', '0002_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.FileField(upload_to='land_images/'),
        ),
    ]
