# Generated by Django 4.2.1 on 2023-12-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandboxapp', '0004_workspace_sfid_alter_workspace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(default='Delivered', max_length=100),
        ),
    ]
